global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          environment: tau
          location: home
          hardware: pi

  - job_name: cadvisor
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets:
          - cadvisor.tau.alexrudy.tech
        labels:
          environment: tau
          location: home
          hardware: pi
      - targets:
          - cadvisor.staging.alexrudy.tech
        labels:
          environment: staging
          location: us-west1
          hardware: linode
      - targets:
          - cadvisor.production.alexrudy.tech
        labels:
          environment: production
          location: us-west1
          hardware: linode

  - job_name: "node-exporter"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets:
          - node-exporter.tau.alexrudy.tech
        labels:
          environment: tau
          location: home
          hardware: pi
      - targets:
          - node-exporter.staging.alexrudy.tech
        labels:
          environment: staging
          location: us-west1
          hardware: linode
      - targets:
          - node-exporter.production.alexrudy.tech
        labels:
          environment: production
          location: us-west1
          hardware: linode
