global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          environment: tau
          location: home
          hardware: pi

  - job_name: cadvisor
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets:
          - cadvisor.tau.alexrudy.tech
        labels:
          environment: tau
          location: home
          hardware: pi
      - targets:
          - cadvisor.staging.alexrudy.tech
        labels:
          environment: staging
          location: us-west1
          hardware: linode
      - targets:
          - cadvisor.production.alexrudy.tech
        labels:
          environment: production
          location: us-west1
          hardware: linode

  - job_name: "node-exporter"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets:
          - node-exporter.tau.alexrudy.tech
        labels:
          environment: tau
          location: home
          hardware: pi
      - targets:
          - node-exporter.staging.alexrudy.tech
        labels:
          environment: staging
          location: us-west1
          hardware: linode
      - targets:
          - node-exporter.production.alexrudy.tech
        labels:
          environment: production
          location: us-west1
          hardware: linode

  - job_name: "snmp"
    static_configs:
      - targets:
          - 192.168.0.1
    metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.22.0.1:9116 # The SNMP exporter's real hostname:port.

  # Global exporter-level metrics
  - job_name: "snmp_exporter"
    static_configs:
      - targets: ["172.22.0.1:9116"]
